// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package core

import (
	"github.com/media-streaming-mesh/msm-cp/internal/config"
	"github.com/media-streaming-mesh/msm-cp/internal/rtm"
)

// Injectors from wire.go:

func InitApp() (*App, error) {
	cfg := config.New()
	protocol := rtm.New(cfg)
	app := &App{
		cfg:     cfg,
		rpcImpl: protocol,
	}
	return app, nil
}
