apiVersion: v1
kind: ServiceAccount
metadata:
  name: msm-cni
  namespace: default
  labels:
    app: msm-cni
---

kind: ConfigMap
apiVersion: v1
metadata:
  name: msm-cni-config
  namespace: default
  labels:
    app: msm-cni
data:
  # The CNI network configuration to chain with an existing CNI plugin on each node.
  cni_network_config: |-
    {
      "cniVersion": "0.3.1",
      "name": "msm-cni",
      "type": "msm-cni",
      "logLevel": "error",
      "kubernetes": {
          "kubeConfig": "__KUBECONFIG_FILEPATH__",
          "cniBinDir": "/opt/cni/bin",
          "excludeNamespaces": [ "msm-system" ]
      }
    }
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: msm-cni
  labels:
    app: msm-cni
rules:
  - apiGroups: [""]
    resources:
      - pods
      - nodes
    verbs:
      - get
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: msm-cni
  labels:
    app: msm-cni
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: msm-cni
subjects:
  - kind: ServiceAccount
    name: msm-cni
    namespace: default

