apiVersion: v1
kind: ConfigMap
metadata:
  name: msm-proxy-cfg
  namespace: default
data:
  conf.yml: |
    readTimeout: 5s
    writeTimeout: 5s
    server:
      protocols: [ tcp, udp ]
      rtspPort: 8554
      rtpPort: 8050
      rtcpPort: 8051
