apiVersion: v1
kind: Service
metadata:
  name: msm-proxy
  labels:
    msm: proxy
spec:
  clusterIP: 10.96.5.1
  ports:
    - name: grpc
      port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    msm: proxy
