apiVersion: v1
kind: Service
metadata:
  name: rtsp-server
  labels:
    app: rtsp
spec:
  clusterIP: 10.96.10.1
  ports:
    - name: rtsp
      port: 554
      targetPort: 554
      protocol: TCP
    - name: rtp
      port: 8000
      targetPort: 8000
      protocol: UDP
    - name: rtcp
      port: 8001
      targetPort: 8001
      protocol: UDP
  selector:
    app: rtsp
