apiVersion: v1
kind: Service
metadata:
  name: msm-admission-webhook-svc
  labels:
    app: msm-admission-webhook
spec:
  clusterIP: 10.96.4.1
  ports:
    - port: 443
      targetPort: 443
  selector:
    app: msm-admission-webhook

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msm-admission-webhook
  labels:
    app: msm-admission-webhook
spec:
  selector:
    matchLabels:
      app: msm-admission-webhook
  template:
    metadata:
      labels:
        app: msm-admission-webhook
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      serviceAccount: msm-admission-webhook-sa
      containers:
        - name: msm-admission-webhook
          image: ciscolabs/msm-admission-webhook:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: REPO
              value: "ciscolabs"
            - name: TAG
              value: "latest"
            - name: MSM_SIDECAR
              value: "msm-rtsp-stub"
            - name: IMAGE_PULL_POLICY
              value: IfNotPresent
            - name: "LOG_LVL"
              value: "DEBUG"

