apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rtsp-client
  labels:
    rtsp: client
  namespace: default
spec:
  selector:
    matchLabels:
      rtsp: client
  template:
    metadata:
      labels:
        rtsp: client
      annotations:
        sidecar.mediastreamingmesh.io/inject: "true"
    spec:
      containers:
        - name: stub
          image: stub:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: CONTROL_PLANE
              value: "http://10.96.3.1:9000"
            - name: LEVEL
              value: "DEBUG"
            - name: PORT
              value: "8554"
          ports:
            - name: grpc
              protocol: TCP
              containerPort: 9000
          securityContext:
            runAsGroup: 1337
            runAsUser: 1337
            allowPrivilegeEscalation: false
        - name: rtsp-client
          image: ciscolabs/msm-stub:latest
          imagePullPolicy: IfNotPresent