apiVersion: apps/v1
kind: Deployment
metadata:
  name: msm-controller
  labels:
    msm: controller
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      msm: controller
  template:
    metadata:
      labels:
        msm: controller
      annotations:
        sidecar.mediastreamingmesh.io/inject: "true"
    spec:
      containers:
        - name: msm-controller
          image: msm-controller:latest
          imagePullPolicy: Never
          ports:
            - name: grpc
              protocol: TCP
              containerPort: 9000